FROM python:3.11-slim

WORKDIR /app

COPY ./requirements.txt /app/
RUN pip install --default-timeout=100 --upgrade pip -r /app/requirements.txt

COPY ./app /app/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]